name: connect_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  avatar_glow: ^2.0.2
  badges: ^2.0.3
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.3.1
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.2
  dropdown_search: ^2.0.1
  flutter_native_splash: ^2.1.2+1
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  firebase_auth: ^4.2.4
  flutter_svg: ^1.0.3
  flutter_quill: ^6.1.11
  get: ^4.6.1
  image_picker: ^0.8.4+11
  lottie: ^1.2.2
  intl: ^0.17.0
  introduction_screen: ^3.0.0
  nb_utils: ^4.4.14
  universal_platform: 1.0.0+1
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  photo_view: ^0.13.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
  fonts: 
    - family: Nunito
      fonts: 
        - asset: fonts/Nunito-Regular.ttf
    - family: RobotoSlab
      fonts: 
        - asset: fonts/RobotoSlab-Bold.ttf
  uses-material-design: true

flutter_native_splash: 
  image: images/connect_biru.png
  color: '#F2F2F2'

flutter_icons: 
  android: launcher_icon
  image_path: images/connect_biru.png
  remove_alpha_ios: true
  ios: true

