name: connect_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_auth: ^4.2.4
  nb_utils: ^4.4.14
  dropdown_search: ^2.0.1
  intl: ^0.17.0
  file_picker: ^4.4.0
  image_picker: ^0.8.4+11
  badges: ^2.0.2
  introduction_screen: ^3.0.0
  avatar_glow: ^2.0.2
  lottie: ^1.2.2
  flutter_native_splash: ^2.1.2+1
  # pdf: ^3.7.3
  # path_provider: ^2.0.9
  # open_file: ^3.2.1
  # flutter_email_sender: ^5.1.0
  # flutter_share: ^2.0.0
  # crop_image: ^1.0.2
  # printing: ^5.9.1
  # google_fonts: ^3.0.1
  # flutter:
  #   sdk: flutter
  # flutter_localizations:
  #   sdk: flutter
  # email_validator: ^2.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/
  # fonts:
  #   - family: RobotoSlab
  #     fonts:
  #       - asset: fonts/RobotoSlab-Bold.ttf
  #   - family: Nunito
  #     fonts:
  #       - asset: fonts/Nunito-Regular.ttf
  uses-material-design: true

flutter_native_splash:
  image: images/connect_biru.png
  color: "#F2F2F2"

flutter_icons:
  android: launcher_icon
  image_path: images/connect_biru.png
  remove_alpha_ios: true
  ios: true

